In [34]:
import pandas as pd

In [35]:
DATA = 'https://raw.githubusercontent.com/vega/vega-datasets/next/data/movies.json'
df = pd.read_json(DATA)

# Count the number of entries
print(len(df))

3201

### Cambiamos el formato de fecha de 'Dec 31, 2019' a '2019-12-31'

In [36]:
date_field = 'Release Date'

# Change date format from "Dec 31, 2019" to "2019-12-31"
df[date_field] = pd.to_datetime(df[date_field], format='%b %d %Y').dt.strftime('%Y-%m-%d')

# Show
df.head()

,Title,US Gross,Worldwide Gross,US DVD Sales,Production Budget,Release Date,MPAA Rating,Running Time min,Distributor,Source,Major Genre,Creative Type,Director,Rotten Tomatoes Rating,IMDB Rating,IMDB Votes
0,The Land Girls,146083.0,146083.0,NaN,8000000.0,1998-06-12,R,NaN,Gramercy,None,None,None,None,NaN,6.1,1071.0
1,"First Love, Last Rites",10876.0,10876.0,NaN,300000.0,1998-08-07,R,NaN,Strand,None,Drama,None,None,NaN,6.9,207.0
2,I Married a Strange Person,203134.0,203134.0,NaN,250000.0,1998-08-28,None,NaN,Lionsgate,None,Comedy,None,None,NaN,6.8,865.0
3,Let's Talk About Sex,373615.0,373615.0,NaN,300000.0,1998-09-11,None,NaN,Fine Line,None,Comedy,None,None,13.0,NaN,NaN
4,Slam,1009819.0,1087521.0,NaN,1000000.0,1998-10-09,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,None,62.0,3.4,165.0

### Revisamos los generos

In [37]:
genre_field = 'Major Genre'

# Get unique values
df[genre_field].unique()

## Remove rows with None values
df = df[df[genre_field].notnull()]

df[genre_field].unique()

array(['Drama', 'Comedy', 'Musical', 'Thriller/Suspense', 'Adventure',
       'Action', 'Romantic Comedy', 'Horror', 'Western', 'Documentary',
       'Black Comedy', 'Concert/Performance'], dtype=object)

### Revisamos los ratings

In [38]:
rating1 = 'Rotten Tomatoes Rating'
rating2 = 'IMDB Rating'

# Remove rows with None values
df = df[df[rating1].notnull()]
df = df[df[rating2].notnull()]

# Show
df.head()

,Title,US Gross,Worldwide Gross,US DVD Sales,Production Budget,Release Date,MPAA Rating,Running Time min,Distributor,Source,Major Genre,Creative Type,Director,Rotten Tomatoes Rating,IMDB Rating,IMDB Votes
4,Slam,1009819.0,1087521.0,NaN,1000000.0,1998-10-09,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,None,62.0,3.4,165.0
11,Oliver!,37402877.0,37402877.0,NaN,10000000.0,1968-12-11,None,NaN,Sony Pictures,None,Musical,None,None,84.0,7.5,9111.0
21,1776,0.0,0.0,NaN,4000000.0,1972-11-09,PG,NaN,Sony/Columbia,Based on Play,Drama,Historical Fiction,None,57.0,7.0,4099.0
22,1941,34175000.0,94875000.0,NaN,32000000.0,1979-12-14,None,NaN,Universal,Original Screenplay,Comedy,Historical Fiction,Steven Spielberg,33.0,5.6,13364.0
28,Twin Falls Idaho,985341.0,1027228.0,NaN,500000.0,1999-07-30,R,NaN,Sony Pictures Classics,Original Screenplay,Drama,Contemporary Fiction,Michael Polish,77.0,7.1,2810.0

In [39]:
# Count the number of entries
print(len(df))

2131

In [40]:
# Get the year and assign it to a new column
df['year'] = pd.DatetimeIndex(df[date_field]).year

df.head()

,Title,US Gross,Worldwide Gross,US DVD Sales,Production Budget,Release Date,MPAA Rating,Running Time min,Distributor,Source,Major Genre,Creative Type,Director,Rotten Tomatoes Rating,IMDB Rating,IMDB Votes,year
4,Slam,1009819.0,1087521.0,NaN,1000000.0,1998-10-09,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,None,62.0,3.4,165.0,1998
11,Oliver!,37402877.0,37402877.0,NaN,10000000.0,1968-12-11,None,NaN,Sony Pictures,None,Musical,None,None,84.0,7.5,9111.0,1968
21,1776,0.0,0.0,NaN,4000000.0,1972-11-09,PG,NaN,Sony/Columbia,Based on Play,Drama,Historical Fiction,None,57.0,7.0,4099.0,1972
22,1941,34175000.0,94875000.0,NaN,32000000.0,1979-12-14,None,NaN,Universal,Original Screenplay,Comedy,Historical Fiction,Steven Spielberg,33.0,5.6,13364.0,1979
28,Twin Falls Idaho,985341.0,1027228.0,NaN,500000.0,1999-07-30,R,NaN,Sony Pictures Classics,Original Screenplay,Drama,Contemporary Fiction,Michael Polish,77.0,7.1,2810.0,1999

In [41]:
# Create column for the rotten tomatoes rating average taking into account the year and genre
df['Rotten Tomatoes Rating Avg'] = df.groupby(['year', genre_field])[rating1].transform('mean')

# Create column for the IMDB rating average taking into account the year and genre
df['IMDB Rating Avg'] = df.groupby(['year', genre_field])[rating2].transform('mean')

# Show
df.head()

,Title,US Gross,Worldwide Gross,US DVD Sales,Production Budget,Release Date,MPAA Rating,Running Time min,Distributor,Source,Major Genre,Creative Type,Director,Rotten Tomatoes Rating,IMDB Rating,IMDB Votes,year,Rotten Tomatoes Rating Avg,IMDB Rating Avg
4,Slam,1009819.0,1087521.0,NaN,1000000.0,1998-10-09,R,NaN,Trimark,Original Screenplay,Drama,Contemporary Fiction,None,62.0,3.4,165.0,1998,65.448276,6.544828
11,Oliver!,37402877.0,37402877.0,NaN,10000000.0,1968-12-11,None,NaN,Sony Pictures,None,Musical,None,None,84.0,7.5,9111.0,1968,84.000000,7.500000
21,1776,0.0,0.0,NaN,4000000.0,1972-11-09,PG,NaN,Sony/Columbia,Based on Play,Drama,Historical Fiction,None,57.0,7.0,4099.0,1972,57.000000,7.000000
22,1941,34175000.0,94875000.0,NaN,32000000.0,1979-12-14,None,NaN,Universal,Original Screenplay,Comedy,Historical Fiction,Steven Spielberg,33.0,5.6,13364.0,1979,33.000000,5.600000
28,Twin Falls Idaho,985341.0,1027228.0,NaN,500000.0,1999-07-30,R,NaN,Sony Pictures Classics,Original Screenplay,Drama,Contemporary Fiction,Michael Polish,77.0,7.1,2810.0,1999,56.666667,6.647619

In [42]:
# Export to JSON
df.to_json('movies.json', orient='records')